### ISSUE TITLE
缺少部分包

### ISSUE THREAD

**Issue by zhaikaishun** [hetianyi/easy-sync#1]
com.hty.baseframe 包
com.jcraft包
com.hty.util.ftp包
等等

**Comment by hetianyi** [comment]
这些依赖都在我的其他github项目里面，你可以找一找，com.jcraft是第三方包，maven中央仓库可以下载到。

在 2018年1月5日，15:30，zhaikaishun <notifications@github.com<mailto:notifications@github.com>> 写道：


com.hty.baseframe 包
com.jcraft包
com.hty.util.ftp包
等等

**Comment by zhaikaishun** [comment]
嗯嗯，thanks，解决了
