### ISSUE TITLE
仓库依赖包无法下载

### ISSUE THREAD

**Issue by xuluhang** [hetianyi/easy-sync#2]
com.hty.util
com.hty.baseframe
这两个包在仓库中找不到了

**Comment by hetianyi** [comment]
先clone：
https://github.com/hetianyi/common-ftp
并执行mvn install
之后再mvn install本项目即可

**Comment by kanong** [comment]
https://github.com/hetianyi/common-ftp   这个项目mvn install 后可以解决com.hty.util，但是不包含com.hty.baseframe这个，看了你所有的项目，没有找到，麻烦上传下这个项目吧？
