### ISSUE TITLE
有两个依赖包找不到

### ISSUE THREAD

**Issue by kanong** [hetianyi/easy-sync#3]
1、com.hty.util
2、com.hty.baseframe

https://github.com/hetianyi/common-ftp 这个项目mvn install 后可以解决com.hty.util，但是不包含com.hty.baseframe这个，看了你所有的项目，没有找到，麻烦上传下这个项目吧？

**Comment by hetianyi** [comment]
https://github.com/hetianyi/baseframe-common
已上传！
